In [3]:
import numpy as np

In [8]:
#create two vectors
a, b = np.random.rand(3,), np.random.rand(3,)
a, b

(array([0.12731372, 0.293379  , 0.76174757]),
 array([0.63507587, 0.04497867, 0.16349613]))

In [10]:
np.dot(a,b), np.cross(a,b), np.linalg.norm(a)

(0.2185924470942216,
 array([ 0.01370394,  0.4629522 , -0.18059152]),
 0.8261594217704802)